DATA:
  DATASET: "food_subset"
  NUM_CLASSES: 5
  CLASSES: ['prime_rib', 'pork_chop', 'steak', 'baby_back_ribs', 'filet_mignon']
  SPLIT: 'split'
  FOOD_SUBSET_DIR: 'food-101-redmeat'
  BATCH_SIZE: 96
  USE_CLASS_WEIGHTS: True

EXP:
  APPROACH: "generic"
  MODEL: "resnet50"
  PRETRAINED: True

  LOSSES:
    CLASSIFICATION:
      WEIGHT: 1

  NUM_EPOCHS: 150
  OPTIMIZER: "SGD"
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  SCHEDULER: "NONE"

  BASE:
    LR: 0.01

  CLASSIFIER:
    LR: 0.001
