DATA:
  ROOT: "/home/ryreu/guided_cnn/Food101/data"
  DATASET: "food_subset"
  FOOD_SUBSET_DIR: "food-101-redmeat"
  ATTENTION_DIR: "NONE"
  SIZE: 224
  CLASSES: ['prime_rib', 'pork_chop', 'steak', 'baby_back_ribs', 'filet_mignon']
  SPLIT: 'split'

APPROACH: "clip"

SAVE_FOLDER: "clip_vit_attention"
MODEL_TYPE: "ViT-B/32"
ATTENTION_TYPE: "transformer"

PROMPTS: ["an image of meat", "a photo of meat"]
