DATA:
  DATASET: "food_subset"
  NUM_CLASSES: 5
  SEPARATE_CLASSES: False

  BATCH_SIZE: 96

  USE_CLASS_WEIGHTS: True
  USE_GROUP_WEIGHTS: False
  CLASSES: ['prime_rib', 'pork_chop', 'steak', 'baby_back_ribs', 'filet_mignon']
  SUBDIR: 'food-101'
  FOOD_SUBSET_DIR: 'food-101'
  SPLIT: 'split'

EXP:
  APPROACH: "generic"
  NUM_TRIALS: 1

  MODEL: "resnet50"
  PRETRAINED: True

  LOSSES:
    CLASSIFICATION:
      WEIGHT: 1

  NUM_EPOCHS: 150
  OPTIMIZER: "SGD"
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9

  SCHEDULER: "NONE"

  BASE:
    LR: 0.001

  CLASSIFIER:
    LR: 0.001

