DATA:
  DATASET: "waterbirds"
  BATCH_SIZE: 96
  NUM_CLASSES: 2
  CONFOUNDING_FACTOR: 1.0
  WATERBIRDS_DIR: "waterbird_1.0_forest2water2"
  ATTENTION_DIR: "clip_vit_attention"

EXP:
  APPROACH: "generic"

  MODEL: "resnet50"
  PRETRAINED: True

  LOSSES:
    CLASSIFICATION:
      WEIGHT: 1
    GRADIENT_OUTSIDE:
      COMPUTE: True
      LOG: False
      WEIGHT: 10000
      CRITERION: "L1"
      GT: "clip_vit"
      COMBINE_ATT_MODE: "average_nonzero"

  NUM_EPOCHS: 200
  OPTIMIZER: "SGD"
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  SCHEDULER: "NONE"

  BASE:
    LR: 0.005

  CLASSIFIER:
    LR: 0.0001

